name: build-jammy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-docker-images: 'true'
          remove-swapfile: 'true'

      - name: Clean up APT cache
        run: sudo apt-get clean

      - name: Autoremove and Autoclean
        run: |
          sudo apt-get autoremove -y
          sudo apt-get autoclean

      - name: Remove Docker images
        run: docker system prune -af

      - name: Remove temporary files
        run: sudo rm -rf /tmp/*

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-


      - name: Build
        run: |
          cd scripts
          ./build.sh -
          cd ..
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flower
          path: |
            scripts/flower.iso
            scripts/image/md5sum.txt
